server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Vue Router en mode history : toutes les requêtes → index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
